### ISSUE TITLE
ValueError:Tensor type torch.cuda.CharTensor is not supported.

### ISSUE THREAD

**Issue by Tonyhukaifan** [sands-lab/grace#2]
@hangxu0304 I run the QSGD algorithm with 4 GPUs with an error. 
```
compression = Allreduce(QSGDCompressor(127), NoneMemory())

# Horovod: wrap optimizer with DistributedOptimizer.
optimizer = hvd.DistributedOptimizer(optimizer, compression, named_parameters=model.named_parameters())
```
The error message is
```
Traceback (most recent call last):
  File "./trainer.py", line 442, in <module>
    main()
  File "./trainer.py", line 235, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 292, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 54, in send_step
    handles = self.async_send(tensors_compressed, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allreduce.py", line 10, in async_send
    handles.append(allreduce_async_(tensor_compressed, self.compressor.average, name + str(i)))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 186, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 88, in _allreduce_async
    function = _check_function(_allreduce_function_factory, tensor)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 72, in _check_function
    raise ValueError('Tensor type %s is not supported.' % tensor.type())
ValueError: Tensor type torch.cuda.CharTensor is not supported.
Traceback (most recent call last):
  File "./trainer.py", line 442, in <module>
    main()
  File "./trainer.py", line 235, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 292, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 54, in send_step
    handles = self.async_send(tensors_compressed, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allreduce.py", line 10, in async_send
    handles.append(allreduce_async_(tensor_compressed, self.compressor.average, name + str(i)))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 186, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 88, in _allreduce_async
    function = _check_function(_allreduce_function_factory, tensor)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 72, in _check_function
    raise ValueError('Tensor type %s is not supported.' % tensor.type())
ValueError: Tensor type torch.cuda.CharTensor is not supported.
Traceback (most recent call last):
  File "./trainer.py", line 442, in <module>
    main()
  File "./trainer.py", line 235, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 292, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 54, in send_step
    handles = self.async_send(tensors_compressed, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allreduce.py", line 10, in async_send
    handles.append(allreduce_async_(tensor_compressed, self.compressor.average, name + str(i)))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 186, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 88, in _allreduce_async
    function = _check_function(_allreduce_function_factory, tensor)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 72, in _check_function
    raise ValueError('Tensor type %s is not supported.' % tensor.type())
ValueError: Tensor type torch.cuda.CharTensor is not supported.
Traceback (most recent call last):
  File "./trainer.py", line 442, in <module>
    main()
  File "./trainer.py", line 235, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 292, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 54, in send_step
    handles = self.async_send(tensors_compressed, name)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allreduce.py", line 10, in async_send
    handles.append(allreduce_async_(tensor_compressed, self.compressor.average, name + str(i)))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 186, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 88, in _allreduce_async
    function = _check_function(_allreduce_function_factory, tensor)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 72, in _check_function
    raise ValueError('Tensor type %s is not supported.' % tensor.type())
ValueError: Tensor type torch.cuda.CharTensor is not supported.
yhrun: error: gpu16: tasks 0-3: Exited with exit code 1
```
Could you help me? Thanks.

**Comment by Tonyhukaifan** [comment]
The error disappeared when I make the quantum_num no less than 128. Any reasons?

**Comment by hangxu0304** [comment]
You need to use Allgather for QSGD, since for these compressors Allreduce the compressed gradients directly does not make any sense.

**Comment by Tonyhukaifan** [comment]
I will have a try. Thanks a lot.

**Comment by Tonyhukaifan** [comment]
```
compression = Allgather(QSGDCompressor(127), NoneMemory(), hvd.size())
```
I have used the `Allgather` and there also have an error
```
Traceback (most recent call last):
  File "./trainer.py", line 444, in <module>
    main()
  File "./trainer.py", line 237, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 295, in train
    optimizer.step()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 175, in synchronize
    tensor = self.grace.receive_step(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 58, in receive_step
    return self.wait_receive(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allgather.py", line 38, in wait_receive
    gathered = synchronize(handle)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 446, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: Rank zero tried to ALLGATHER a rank-zero tensor.
Traceback (most recent call last):
  File "./trainer.py", line 444, in <module>
    main()
  File "./trainer.py", line 237, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 295, in train
    optimizer.step()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 175, in synchronize
    tensor = self.grace.receive_step(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 58, in receive_step
    return self.wait_receive(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allgather.py", line 38, in wait_receive
    gathered = synchronize(handle)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 446, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: Rank zero tried to ALLGATHER a rank-zero tensor.
Traceback (most recent call last):
  File "./trainer.py", line 444, in <module>
    main()
  File "./trainer.py", line 237, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 295, in train
    optimizer.step()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 175, in synchronize
    tensor = self.grace.receive_step(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 58, in receive_step
    return self.wait_receive(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allgather.py", line 38, in wait_receive
    gathered = synchronize(handle)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 446, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: Rank zero tried to ALLGATHER a rank-zero tensor.
Traceback (most recent call last):
  File "./trainer.py", line 444, in <module>
    main()
  File "./trainer.py", line 237, in main
    train(train_loader, model, criterion, optimizer, epoch, log=log)
  File "./trainer.py", line 295, in train
    optimizer.step()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 213, in step
    self.synchronize()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/__init__.py", line 175, in synchronize
    tensor = self.grace.receive_step(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/__init__.py", line 58, in receive_step
    return self.wait_receive(handles, ctx)
  File "/GPUFS/nudt_chkwu_2/kfhu/grace-master/grace_dl/torch/communicator/allgather.py", line 38, in wait_receive
    gathered = synchronize(handle)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/torch_ho/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 446, in synchronize
    mpi_lib.horovod_torch_wait_and_clear(handle)
RuntimeError: Rank zero tried to ALLGATHER a rank-zero tensor.
yhrun: error: gpu16: tasks 0-3: Exited with exit code 1
```

**Comment by hangxu0304** [comment]
This bug is just fixed. see [here](https://github.com/sands-lab/grace/commit/555ca7bf18a921eeb7cd3d8ccbe77d9bf5dd8636)
