### ISSUE TITLE
TypeError:compensate() missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by Tonyhukaifan** [sands-lab/grace#7]
I use the GRACE to train the NLP model with PennTreeBank dataset in a distributed manner. And there is an error followed I couldn't solve. 
```
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    train(epoch, trainloader, model, optimizer, device, batch_size)
  File "main.py", line 132, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Horovod/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "../grace_dl/torch/__init__.py", line 51, in send_step
    tensor = self.memory.compensate(tensor, name)
TypeError: compensate() missing 1 required positional argument: 'name'
```
It seems that the function `compensate` can't get the right argument `name`. Any help is appreciated. Thanks!

**Comment by hangxu0304** [comment]
Could you please provide your training script and command for us to reproduce this bug?

**Comment by Tonyhukaifan** [comment]
[NLPCode.zip](https://github.com/sands-lab/grace/files/4889438/NLPCode.zip)
The training scripts are in the `NLPCode.zip`. The command is just like `Horovodrun -np 4 python main.py`  or any other command like `mpirun ...... python main.py`. The dataset could be download at (http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz) and unzip to the path `./data/ptb/`.

**Comment by hangxu0304** [comment]
The bug is caused by ``compression = Allgather(NoneCompressor, NoneMemory, hvd.size())`` in your script. The correct way to initialize grace instance is:
```
compression = Allreduce(NoneCompressor(), NoneMemory()) 
compression = Allreduce(RandomKCompressor(0.1), ResidualMemory())
compression = Allgather(TopKCompressor(0.01), ResidualMemory(), hvd.size())
compression = Allgather(QSGDCompressor(127), NoneMemory(), hvd.size())
```

Besides, we fixed another bug when using allgather for compression in your script. This bug is caused by horovod not GRACE. So you need to do the following changes to `horovod/torch/__init__.py`:
Replace this [line](https://github.com/horovod/horovod/blob/bb2134b427e0e0c5a83624d02fafa4f14de623d9/horovod/torch/__init__.py#L147) with:
```
for param_group in self.param_groups:  
    for p in param_group['params']:  
        if p in missing_p:
```

**Comment by Tonyhukaifan** [comment]
I have initialized the instance and replaced that line with your advice and there also is an error about `compensate()`:
```
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    train(epoch, trainloader, model, optimizer, device, batch_size)
  File "main.py", line 132, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "../grace_dl/torch/__init__.py", line 51, in send_step
    tensor = self.memory.compensate(tensor, name)
TypeError: compensate() missing 1 required positional argument: 'name'
```

**Comment by hangxu0304** [comment]
It should work. Please double check your code with this copy. 
[main.py.zip](https://github.com/sands-lab/grace/files/4895181/main.py.zip)

**Comment by Tonyhukaifan** [comment]
Sorry for my carelessness. Thanks, it works. But another bug appears.
```
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    train(epoch, trainloader, model, optimizer, device, batch_size)
  File "main.py", line 119, in train
    optimizer.synchronize()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 178, in synchronize
    tensor = self.grace.receive_step(handles, ctx)
  File "../grace_dl/torch/__init__.py", line 58, in receive_step
    return self.wait_receive(handles, ctx)
  File "../grace_dl/torch/communicator/allgather.py", line 39, in wait_receive
    tensors_ag.append(gathered.split(sizes))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/tensor.py", line 329, in split
    return super(Tensor, self).split_with_sizes(split_size, dim)
RuntimeError: start (0) + length (15000000) exceeds dimension size (40000).
```

**Comment by hangxu0304** [comment]
I guess you are using allgather for high rank compressed tensors. If this is the case, please update grace according to [this](https://github.com/sands-lab/grace/commit/94f31a510cfbadd76f67656d16efbad9b85f56ee).

**Comment by hangxu0304** [comment]
> The bug is caused by `compression = Allgather(NoneCompressor, NoneMemory, hvd.size())` in your script. The correct way to initialize grace instance is:
> 
> ```
> compression = Allreduce(NoneCompressor(), NoneMemory()) 
> compression = Allreduce(RandomKCompressor(0.1), ResidualMemory())
> compression = Allgather(TopKCompressor(0.01), ResidualMemory(), hvd.size())
> compression = Allgather(QSGDCompressor(127), NoneMemory(), hvd.size())
> ```
> 
> Besides, we fixed another bug when using allgather for compression in your script. This bug is caused by horovod not GRACE. So you need to do the following changes to `horovod/torch/__init__.py`:
> Replace this [line](https://github.com/horovod/horovod/blob/bb2134b427e0e0c5a83624d02fafa4f14de623d9/horovod/torch/__init__.py#L147) with:
> 
> ```
> for param_group in self.param_groups:  
>     for p in param_group['params']:  
>         if p in missing_p:
> ```

Hi @karatse , please consider to include this change in the patch file for `horovod/torch/__init__.py`. This bug appears in some specific models where during the training `missing_p` is not empty, and due to the set operation, the order of variables in `missing_p` are different across the workers. Thus when horovod tries to allgather the variables in the set, mismatch could happen.

**Comment by Tonyhukaifan** [comment]
`compression = Allreduce(NoneCompressor(), NoneMemory())`
I use the compression above and train the LSTM model, but the Horovod has been shutdown. 
```
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    train(epoch, trainloader, model, optimizer, device, batch_size)
  File "main.py", line 116, in train
    loss.backward()
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
    handle, ctx = self._communicate_grad_async(p)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
    handle, ctx = self.grace.send_step(tensor, name)
  File "../grace_dl/torch/__init__.py", line 54, in send_step
    handles = self.async_send(tensors_compressed, name)
  File "../grace_dl/torch/communicator/allreduce.py", line 10, in async_send
    handles.append(allreduce_async_(tensor_compressed, self.compressor.average, name + str(i)))
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 186, in allreduce_async_
    return _allreduce_async(tensor, tensor, average, name)
  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 90, in _allreduce_async
    name.encode() if name is not None else _NULL)
RuntimeError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
```
The LSTM model has nearly 66 million of parameters. Is it too many parameters that caused Horovod to crash?

**Comment by hangxu0304** [comment]
It won't be this reason I guess, since we have successfully used GRACE to train BERT base (110 million parameters). However, we don't have this issue with your training script in our env, it runs properly.

**Comment by Tonyhukaifan** [comment]
@hangxu0304 When I use the `Allgather()` to train a NLP model, a bug appears as follow:
```
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "main.py", line 309, in <module>
[1,0]<stderr>:    train(epoch, trainloader, model, optimizer, args.clip, log=writer)
[1,0]<stderr>:  File "main.py", line 129, in train
[1,0]<stderr>:    loss.backward()
[1,0]<stderr>:  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
[1,0]<stderr>:    torch.autograd.backward(self, gradient, retain_graph, create_graph)
[1,0]<stderr>:  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
[1,0]<stderr>:    allow_unreachable=True)  # allow_unreachable flag
[1,0]<stderr>:  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 150, in hook
[1,0]<stderr>:    handle, ctx = self._communicate_grad_async(p)
[1,0]<stderr>:  File "/GPUFS/nudt_chkwu_2/.conda/envs/Grace/lib/python3.6/site-packages/horovod/torch/__init__.py", line 132, in _communicate_grad_async
[1,0]<stderr>:    handle, ctx = self.grace.send_step(tensor, name)
[1,0]<stderr>:  File "../grace_dl/torch/__init__.py", line 54, in send_step
[1,0]<stderr>:    handles = self.async_send(tensors_compressed, name)
[1,0]<stderr>:  File "../grace_dl/torch/communicator/allgather.py", line 18, in async_send
[1,0]<stderr>:    tensors_size = [t.size()[0] for t in tensors_compressed]  # list of tensor size for this rank, allgather on the 1st dimension of the tensor
[1,0]<stderr>:  File "../grace_dl/torch/communicator/allgather.py", line 18, in <listcomp>
[1,0]<stderr>:    tensors_size = [t.size()[0] for t in tensors_compressed]  # list of tensor size for this rank, allgather on the 1st dimension of the tensor
[1,0]<stderr>:IndexError: tuple index out of range
```
Any solutions to it?  Thanks!!!
